spring.application.name=simple-billing
# Configuración de conexión a la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/billing_test
spring.datasource.username=postgres
spring.datasource.password=141124

# Mostrar consultas SQL en consola
spring.jpa.show-sql=true

# Configuración del dialecto para PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configurar esquema por defecto
spring.jpa.properties.hibernate.default_schema=scheme_billing

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true


spring.jpa.hibernate.ddl-auto=update


